<?php
require dirname(__DIR__) . '/bootstrap.php';
$input = request_json();
$idToken = (string)($input['idToken'] ?? '');
if (!$idToken) json_response(['ok' => false, 'error' => 'Missing Google ID token'], 422);
if (empty($config['GOOGLE_CLIENT_ID'])) json_response(['ok' => false, 'error' => 'Google OAuth is not configured'], 500);
$url = 'https://oauth2.googleapis.com/tokeninfo?id_token=' . rawurlencode($idToken);
$ch = curl_init($url);
curl_setopt_array($ch, [CURLOPT_RETURNTRANSFER => true, CURLOPT_TIMEOUT => 10]);
$response = curl_exec($ch);
$status = curl_getinfo($ch, CURLINFO_HTTP_CODE);
curl_close($ch);
if ($status !== 200 || !$response) json_response(['ok' => false, 'error' => 'Google token verification failed'], 401);
$profile = json_decode($response, true);
if (!is_array($profile) || ($profile['aud'] ?? '') !== $config['GOOGLE_CLIENT_ID']) json_response(['ok' => false, 'error' => 'Google token audience mismatch'], 401);
$email = $profile['email'] ?? '';
if (!$email) json_response(['ok' => false, 'error' => 'Google account has no email'], 422);
$mysqli = db($config);
$user = upsert_user_by_email($mysqli, $email, null, $profile['name'] ?? null);
$sub = (string)($profile['sub'] ?? '');
$avatar = (string)($profile['picture'] ?? '');
$stmt = $mysqli->prepare('UPDATE livedash_users SET google_sub = ?, display_name = COALESCE(display_name, ?), avatar_url = ? WHERE id = ?');
$uid = (int)$user['id'];
$stmt->bind_param('sssi', $sub, $profile['name'], $avatar, $uid);
$stmt->execute();
$token = issue_token($mysqli, $uid);
record_event($mysqli, $uid, 'google_sign_in', []);
json_response(['ok' => true, 'token' => $token, 'user' => ['id' => $uid, 'email' => $email, 'displayName' => $profile['name'] ?? null, 'avatarUrl' => $avatar]]);
