import type { FetchedContentsResponse } from '@/services/hooks/content/get-content.hook'

const simpleIconMap: Record<string, string> = {
	'1password.com': '1password',
	'adobe.com': 'adobe',
	'airbnb.com': 'airbnb',
	'amazon.com': 'amazon',
	'apple.com': 'apple',
	'apnews.com': 'apnews',
	'archive.org': 'internetarchive',
	'asana.com': 'asana',
	'aws.amazon.com': 'aws',
	'bbc.com': 'bbc',
	'behance.net': 'behance',
	'bestbuy.com': 'bestbuy',
	'binance.com': 'binance',
	'bloomberg.com': 'bloomberg',
	'booking.com': 'booking',
	'brilliant.org': 'brilliant',
	'calendly.com': 'calendly',
	'camelcamelcamel.com': 'camelcamelcamel',
	'canva.com': 'canva',
	'chat.openai.com': 'openai',
	'claude.ai': 'claude',
	'clickup.com': 'clickup',
	'cloudflare.com': 'cloudflare',
	'coinbase.com': 'coinbase',
	'coingecko.com': 'coingecko',
	'coinmarketcap.com': 'coinmarketcap',
	'consensus.app': 'consensus',
	'copilot.microsoft.com': 'copilot',
	'coursera.org': 'coursera',
	'deepl.com': 'deepl',
	'developer.mozilla.org': 'mdn',
	'dhl.com': 'dhl',
	'discord.com': 'discord',
	'docker.com': 'docker',
	'docusign.com': 'docusign',
	'dribbble.com': 'dribbble',
	'dropbox.com': 'dropbox',
	'duolingo.com': 'duolingo',
	'ebay.com': 'ebay',
	'edx.org': 'edx',
	'elicit.com': 'elicit',
	'etsy.com': 'etsy',
	'europa.eu': 'europa',
	'european-union.europa.eu': 'europa',
	'euronews.com': 'euronews',
	'figma.com': 'figma',
	'finance.yahoo.com': 'yahoo',
	'ft.com': 'ft',
	'github.com': 'github',
	'gitlab.com': 'gitlab',
	'gmail.com': 'gmail',
	'google.com': 'google',
	'gov.uk': 'govuk',
	'grammarly.com': 'grammarly',
	'huggingface.co': 'huggingface',
	'idealo.de': 'idealo',
	'ikea.com': 'ikea',
	'instagram.com': 'instagram',
	'investing.com': 'investing',
	'irs.gov': 'irs',
	'joinhoney.com': 'honey',
	'khanacademy.org': 'khanacademy',
	'kraken.com': 'kraken',
	'linear.app': 'linear',
	'linkedin.com': 'linkedin',
	'loom.com': 'loom',
	'mail.google.com': 'gmail',
	'maps.google.com': 'googlemaps',
	'midjourney.com': 'midjourney',
	'miro.com': 'miro',
	'mit.edu': 'fallback',
	'netlify.com': 'netlify',
	'news.google.com': 'googlenews',
	'news.ycombinator.com': 'ycombinator',
	'notion.so': 'notion',
	'npmjs.com': 'npm',
	'ocw.mit.edu': 'fallback',
	'openai.com': 'openai',
	'openstax.org': 'openstax',
	'outlook.live.com': 'outlook',
	'paypal.com': 'paypal',
	'perplexity.ai': 'perplexity',
	'phind.com': 'phind',
	'pinterest.com': 'pinterest',
	'postman.com': 'postman',
	'producthunt.com': 'producthunt',
	'reddit.com': 'reddit',
	'reuters.com': 'reuters',
	'revolut.com': 'revolut',
	'runwayml.com': 'runway',
	'scholar.google.com': 'googlescholar',
	'shopping.google.com': 'googleshopping',
	'skyscanner.net': 'skyscanner',
	'slack.com': 'slack',
	'spotify.com': 'spotify',
	'stackoverflow.com': 'stackoverflow',
	'stripe.com': 'stripe',
	'supabase.com': 'supabase',
	'target.com': 'target',
	'techcrunch.com': 'techcrunch',
	'ted.com': 'ted',
	'telegram.org': 'telegram',
	'theguardian.com': 'theguardian',
	'thetrainline.com': 'trainline',
	'theverge.com': 'theverge',
	'todoist.com': 'todoist',
	'tradingview.com': 'tradingview',
	'trello.com': 'trello',
	'uber.com': 'uber',
	'udemy.com': 'udemy',
	'ups.com': 'ups',
	'vercel.com': 'vercel',
	'walmart.com': 'walmart',
	'web.telegram.org': 'telegram',
	'web.whatsapp.com': 'whatsapp',
	'whatsapp.com': 'whatsapp',
	'wikipedia.org': 'wikipedia',
	'wise.com': 'wise',
	'wolframalpha.com': 'wolfram',
	'x.com': 'x',
	'youtube.com': 'youtube',
	'zoom.us': 'zoom',
}

const domainFromUrl = (url: string) => new URL(url).hostname.replace(/^www\./, '')
const iconFor = (url: string, domain?: string) => {
	const cleanDomain = (domain || domainFromUrl(url)).replace(/^www\./, '')
	const key = simpleIconMap[cleanDomain] || simpleIconMap[domainFromUrl(url)]
	return `/live-assets/site-icons/${key || 'fallback'}.svg`
}

const favicon = (domain: string) => iconFor(`https://${domain}`, domain)

const site = (name: string, url: string, domain?: string) => ({
	name,
	url,
	type: 'SITE' as const,
	icon: iconFor(url, domain),
	hasBorder: false,
	isNew: false,
})

export const localContents: FetchedContentsResponse = {
	contents: [
		{
			id: 'daily',
			category: 'Daily Essentials',
			icon: favicon('google.com'),
			badges: [{ label: 'Core', bgColor: '#3158ff', textColor: '#fff' }],
			links: [
				site('Google', 'https://www.google.com'),
				site('Gmail', 'https://mail.google.com', 'gmail.com'),
				site('Calendar', 'https://calendar.google.com'),
				site('Drive', 'https://drive.google.com'),
				site('Outlook', 'https://outlook.live.com'),
				site('Notion', 'https://www.notion.so'),
				site('Todoist', 'https://todoist.com'),
				site('Slack', 'https://slack.com'),
				site('Zoom', 'https://zoom.us'),
				site('Dropbox', 'https://dropbox.com'),
				site('1Password', 'https://1password.com'),
				site('Wikipedia', 'https://wikipedia.org'),
			],
		},
		{
			id: 'ai',
			category: 'AI & Research',
			icon: favicon('openai.com'),
			badges: [{ label: 'AI', bgColor: '#8b5cf6', textColor: '#fff' }],
			links: [
				site('ChatGPT', 'https://chat.openai.com', 'openai.com'),
				site('Claude', 'https://claude.ai'),
				site('Perplexity', 'https://www.perplexity.ai'),
				site('Gemini', 'https://gemini.google.com'),
				site('Copilot', 'https://copilot.microsoft.com'),
				site('Hugging Face', 'https://huggingface.co'),
				site('Runway', 'https://runwayml.com'),
				site('Midjourney', 'https://www.midjourney.com'),
				site('DeepL', 'https://www.deepl.com/translator', 'deepl.com'),
				site('Elicit', 'https://elicit.com'),
				site('Consensus', 'https://consensus.app'),
				site('Phind', 'https://www.phind.com'),
			],
		},
		{
			id: 'work',
			category: 'Work & Productivity',
			icon: favicon('notion.so'),
			badges: [],
			links: [
				site('Notion', 'https://www.notion.so'),
				site('Trello', 'https://trello.com'),
				site('Asana', 'https://asana.com'),
				site('Linear', 'https://linear.app'),
				site('ClickUp', 'https://clickup.com'),
				site('Miro', 'https://miro.com'),
				site('Loom', 'https://loom.com'),
				site('Figma', 'https://figma.com'),
				site('Canva', 'https://canva.com'),
				site('Calendly', 'https://calendly.com'),
				site('DocuSign', 'https://www.docusign.com'),
				site('Grammarly', 'https://www.grammarly.com'),
			],
		},
		{
			id: 'development',
			category: 'Development',
			icon: favicon('github.com'),
			badges: [],
			links: [
				site('GitHub', 'https://github.com'),
				site('GitLab', 'https://gitlab.com'),
				site('Stack Overflow', 'https://stackoverflow.com'),
				site('MDN', 'https://developer.mozilla.org'),
				site('Vercel', 'https://vercel.com'),
				site('Netlify', 'https://www.netlify.com'),
				site('Docker Hub', 'https://hub.docker.com'),
				site('npm', 'https://www.npmjs.com'),
				site('Cloudflare', 'https://dash.cloudflare.com', 'cloudflare.com'),
				site('AWS', 'https://aws.amazon.com/console', 'aws.amazon.com'),
				site('Supabase', 'https://supabase.com'),
				site('Postman', 'https://www.postman.com'),
			],
		},
		{
			id: 'crypto-finance',
			category: 'Crypto & Finance',
			icon: favicon('coinmarketcap.com'),
			badges: [{ label: 'Markets', bgColor: '#12b981', textColor: '#fff' }],
			links: [
				site('CoinMarketCap', 'https://coinmarketcap.com'),
				site('CoinGecko', 'https://www.coingecko.com'),
				site('Binance', 'https://www.binance.com'),
				site('Coinbase', 'https://www.coinbase.com'),
				site('Kraken', 'https://www.kraken.com'),
				site('TradingView', 'https://www.tradingview.com'),
				site('Yahoo Finance', 'https://finance.yahoo.com'),
				site('Investing', 'https://www.investing.com'),
				site('Wise', 'https://wise.com'),
				site('Revolut', 'https://www.revolut.com'),
				site('Stripe', 'https://dashboard.stripe.com', 'stripe.com'),
				site('PayPal', 'https://www.paypal.com'),
			],
		},
		{
			id: 'news',
			category: 'News & Signals',
			icon: favicon('reuters.com'),
			badges: [],
			links: [
				site('Reuters', 'https://www.reuters.com'),
				site('BBC', 'https://www.bbc.com/news', 'bbc.com'),
				site('Euronews', 'https://www.euronews.com'),
				site('The Guardian', 'https://www.theguardian.com'),
				site('AP News', 'https://apnews.com'),
				site('Bloomberg', 'https://www.bloomberg.com'),
				site('Financial Times', 'https://www.ft.com'),
				site('The Verge', 'https://www.theverge.com'),
				site('TechCrunch', 'https://techcrunch.com'),
				site('Hacker News', 'https://news.ycombinator.com'),
				site('Product Hunt', 'https://www.producthunt.com'),
				site('Google News', 'https://news.google.com'),
			],
		},
		{
			id: 'travel-public',
			category: 'Travel & Public',
			icon: favicon('booking.com'),
			badges: [{ label: 'EU / US', bgColor: '#eef4ff', textColor: '#3151c8' }],
			links: [
				site('Google Maps', 'https://maps.google.com'),
				site('Google Flights', 'https://www.google.com/travel/flights', 'google.com'),
				site('Booking', 'https://www.booking.com'),
				site('Airbnb', 'https://airbnb.com'),
				site('Skyscanner', 'https://www.skyscanner.net'),
				site('Trainline', 'https://www.thetrainline.com'),
				site('Uber', 'https://uber.com'),
				site('DHL', 'https://www.dhl.com'),
				site('UPS', 'https://www.ups.com/track', 'ups.com'),
				site('GOV.UK', 'https://www.gov.uk'),
				site('EU Portal', 'https://european-union.europa.eu', 'europa.eu'),
				site('IRS', 'https://www.irs.gov'),
			],
		},
		{
			id: 'social-creative',
			category: 'Social & Creative',
			icon: favicon('instagram.com'),
			badges: [],
			links: [
				site('X', 'https://x.com'),
				site('LinkedIn', 'https://linkedin.com'),
				site('Instagram', 'https://instagram.com'),
				site('Reddit', 'https://reddit.com'),
				site('Discord', 'https://discord.com'),
				site('WhatsApp', 'https://web.whatsapp.com'),
				site('Telegram', 'https://web.telegram.org'),
				site('Pinterest', 'https://pinterest.com'),
				site('YouTube', 'https://youtube.com'),
				site('Spotify', 'https://open.spotify.com', 'spotify.com'),
				site('Behance', 'https://www.behance.net'),
				site('Dribbble', 'https://dribbble.com'),
			],
		},
		{
			id: 'shopping',
			category: 'Shopping & Deals',
			icon: favicon('amazon.com'),
			badges: [],
			links: [
				site('Amazon', 'https://www.amazon.com'),
				site('eBay', 'https://www.ebay.com'),
				site('Etsy', 'https://www.etsy.com'),
				site('IKEA', 'https://www.ikea.com'),
				site('Apple', 'https://www.apple.com'),
				site('Best Buy', 'https://www.bestbuy.com'),
				site('Target', 'https://www.target.com'),
				site('Walmart', 'https://www.walmart.com'),
				site('Idealo', 'https://www.idealo.de'),
				site('CamelCamelCamel', 'https://camelcamelcamel.com'),
				site('Honey', 'https://www.joinhoney.com'),
				site('Google Shopping', 'https://shopping.google.com'),
			],
		},
		{
			id: 'learning',
			category: 'Learning',
			icon: favicon('coursera.org'),
			badges: [],
			links: [
				site('Coursera', 'https://www.coursera.org'),
				site('edX', 'https://www.edx.org'),
				site('Khan Academy', 'https://www.khanacademy.org'),
				site('Udemy', 'https://www.udemy.com'),
				site('Duolingo', 'https://www.duolingo.com'),
				site('Brilliant', 'https://brilliant.org'),
				site('MIT OpenCourseWare', 'https://ocw.mit.edu', 'mit.edu'),
				site('Google Scholar', 'https://scholar.google.com', 'scholar.google.com'),
				site('Archive', 'https://archive.org'),
				site('TED', 'https://www.ted.com'),
				site('OpenStax', 'https://openstax.org'),
				site('WolframAlpha', 'https://www.wolframalpha.com'),
			],
		},
	],
}
