import type { FetchedContentsResponse } from '@/services/hooks/content/get-content.hook'

const favicon = (domain: string) =>
	`https://www.google.com/s2/favicons?domain=${domain}&sz=64`

export const localContents: FetchedContentsResponse = {
	contents: [
		{
			id: 'search-ai',
			category: 'Search & AI',
			icon: favicon('google.com'),
			badges: [{ label: 'Daily', bgColor: '#3158ff', textColor: '#fff' }],
			links: [
				{
					name: 'Google',
					url: 'https://www.google.com',
					type: 'SITE',
					icon: '/live-assets/google.svg',
					hasBorder: false,
					isNew: false,
				},
				{
					name: 'ChatGPT',
					url: 'https://chatgpt.com',
					type: 'SITE',
					icon: favicon('chatgpt.com'),
					hasBorder: false,
					isNew: false,
				},
				{
					name: 'Perplexity',
					url: 'https://www.perplexity.ai',
					type: 'SITE',
					icon: favicon('perplexity.ai'),
					hasBorder: false,
					isNew: false,
				},
				{
					name: 'DeepL',
					url: 'https://www.deepl.com/translator',
					type: 'SITE',
					icon: favicon('deepl.com'),
					hasBorder: false,
					isNew: false,
				},
			],
		},
		{
			id: 'productivity',
			category: 'Productivity',
			icon: favicon('notion.so'),
			badges: [],
			links: [
				{
					name: 'Notion',
					url: 'https://www.notion.so',
					type: 'SITE',
					icon: favicon('notion.so'),
					hasBorder: false,
					isNew: false,
				},
				{
					name: 'Gmail',
					url: 'https://mail.google.com',
					type: 'SITE',
					icon: favicon('gmail.com'),
					hasBorder: false,
					isNew: false,
				},
				{
					name: 'Calendar',
					url: 'https://calendar.google.com',
					type: 'SITE',
					icon: favicon('calendar.google.com'),
					hasBorder: false,
					isNew: false,
				},
				{
					name: 'Trello',
					url: 'https://trello.com',
					type: 'SITE',
					icon: favicon('trello.com'),
					hasBorder: false,
					isNew: false,
				},
				{
					name: 'Slack',
					url: 'https://slack.com',
					type: 'SITE',
					icon: favicon('slack.com'),
					hasBorder: false,
					isNew: false,
				},
			],
		},
		{
			id: 'development',
			category: 'Development',
			icon: favicon('github.com'),
			badges: [],
			links: [
				{
					name: 'GitHub',
					url: 'https://github.com',
					type: 'SITE',
					icon: favicon('github.com'),
					hasBorder: false,
					isNew: false,
				},
				{
					name: 'Stack Overflow',
					url: 'https://stackoverflow.com',
					type: 'SITE',
					icon: favicon('stackoverflow.com'),
					hasBorder: false,
					isNew: false,
				},
				{
					name: 'MDN',
					url: 'https://developer.mozilla.org',
					type: 'SITE',
					icon: favicon('developer.mozilla.org'),
					hasBorder: false,
					isNew: false,
				},
				{
					name: 'Vercel',
					url: 'https://vercel.com',
					type: 'SITE',
					icon: favicon('vercel.com'),
					hasBorder: false,
					isNew: false,
				},
			],
		},
		{
			id: 'finance',
			category: 'Finance',
			icon: favicon('wise.com'),
			badges: [],
			links: [
				{
					name: 'Wise',
					url: 'https://wise.com',
					type: 'SITE',
					icon: favicon('wise.com'),
					hasBorder: false,
					isNew: false,
				},
				{
					name: 'Revolut',
					url: 'https://www.revolut.com',
					type: 'SITE',
					icon: favicon('revolut.com'),
					hasBorder: false,
					isNew: false,
				},
				{
					name: 'Yahoo Finance',
					url: 'https://finance.yahoo.com',
					type: 'SITE',
					icon: favicon('finance.yahoo.com'),
					hasBorder: false,
					isNew: false,
				},
				{
					name: 'Investing',
					url: 'https://www.investing.com',
					type: 'SITE',
					icon: favicon('investing.com'),
					hasBorder: false,
					isNew: false,
				},
			],
		},
		{
			id: 'news',
			category: 'News',
			icon: favicon('reuters.com'),
			badges: [],
			links: [
				{
					name: 'Reuters',
					url: 'https://www.reuters.com',
					type: 'SITE',
					icon: favicon('reuters.com'),
					hasBorder: false,
					isNew: false,
				},
				{
					name: 'BBC',
					url: 'https://www.bbc.com/news',
					type: 'SITE',
					icon: favicon('bbc.com'),
					hasBorder: false,
					isNew: false,
				},
				{
					name: 'Euronews',
					url: 'https://www.euronews.com',
					type: 'SITE',
					icon: favicon('euronews.com'),
					hasBorder: false,
					isNew: false,
				},
				{
					name: 'The Guardian',
					url: 'https://www.theguardian.com',
					type: 'SITE',
					icon: favicon('theguardian.com'),
					hasBorder: false,
					isNew: false,
				},
			],
		},
		{
			id: 'travel',
			category: 'Travel',
			icon: favicon('booking.com'),
			badges: [],
			links: [
				{
					name: 'Maps',
					url: 'https://maps.google.com',
					type: 'SITE',
					icon: favicon('maps.google.com'),
					hasBorder: false,
					isNew: false,
				},
				{
					name: 'Booking',
					url: 'https://www.booking.com',
					type: 'SITE',
					icon: favicon('booking.com'),
					hasBorder: false,
					isNew: false,
				},
				{
					name: 'Skyscanner',
					url: 'https://www.skyscanner.net',
					type: 'SITE',
					icon: favicon('skyscanner.net'),
					hasBorder: false,
					isNew: false,
				},
				{
					name: 'Trainline',
					url: 'https://www.thetrainline.com',
					type: 'SITE',
					icon: favicon('thetrainline.com'),
					hasBorder: false,
					isNew: false,
				},
			],
		},
	],
}
