import type { FetchedContentsResponse } from '@/services/hooks/content/get-content.hook'

const favicon = (domain: string) =>
	`https://www.google.com/s2/favicons?domain=${domain}&sz=128`

const site = (name: string, url: string, domain?: string) => ({
	name,
	url,
	type: 'SITE' as const,
	icon: favicon(domain || new URL(url).hostname),
	hasBorder: false,
	isNew: false,
})

export const localContents: FetchedContentsResponse = {
	contents: [
		{
			id: 'daily',
			category: 'Daily Essentials',
			icon: favicon('google.com'),
			badges: [{ label: 'Core', bgColor: '#3158ff', textColor: '#fff' }],
			links: [
				site('Google', 'https://www.google.com'),
				site('Gmail', 'https://mail.google.com', 'gmail.com'),
				site('Calendar', 'https://calendar.google.com'),
				site('Drive', 'https://drive.google.com'),
				site('Outlook', 'https://outlook.live.com'),
				site('Notion', 'https://www.notion.so'),
				site('Todoist', 'https://todoist.com'),
				site('Slack', 'https://slack.com'),
				site('Zoom', 'https://zoom.us'),
				site('Dropbox', 'https://dropbox.com'),
				site('1Password', 'https://1password.com'),
				site('Wikipedia', 'https://wikipedia.org'),
			],
		},
		{
			id: 'ai',
			category: 'AI & Research',
			icon: favicon('openai.com'),
			badges: [{ label: 'AI', bgColor: '#8b5cf6', textColor: '#fff' }],
			links: [
				site('ChatGPT', 'https://chat.openai.com', 'openai.com'),
				site('Claude', 'https://claude.ai'),
				site('Perplexity', 'https://www.perplexity.ai'),
				site('Gemini', 'https://gemini.google.com'),
				site('Copilot', 'https://copilot.microsoft.com'),
				site('Hugging Face', 'https://huggingface.co'),
				site('Runway', 'https://runwayml.com'),
				site('Midjourney', 'https://www.midjourney.com'),
				site('DeepL', 'https://www.deepl.com/translator', 'deepl.com'),
				site('Elicit', 'https://elicit.com'),
				site('Consensus', 'https://consensus.app'),
				site('Phind', 'https://www.phind.com'),
			],
		},
		{
			id: 'work',
			category: 'Work & Productivity',
			icon: favicon('notion.so'),
			badges: [],
			links: [
				site('Notion', 'https://www.notion.so'),
				site('Trello', 'https://trello.com'),
				site('Asana', 'https://asana.com'),
				site('Linear', 'https://linear.app'),
				site('ClickUp', 'https://clickup.com'),
				site('Miro', 'https://miro.com'),
				site('Loom', 'https://loom.com'),
				site('Figma', 'https://figma.com'),
				site('Canva', 'https://canva.com'),
				site('Calendly', 'https://calendly.com'),
				site('DocuSign', 'https://www.docusign.com'),
				site('Grammarly', 'https://www.grammarly.com'),
			],
		},
		{
			id: 'development',
			category: 'Development',
			icon: favicon('github.com'),
			badges: [],
			links: [
				site('GitHub', 'https://github.com'),
				site('GitLab', 'https://gitlab.com'),
				site('Stack Overflow', 'https://stackoverflow.com'),
				site('MDN', 'https://developer.mozilla.org'),
				site('Vercel', 'https://vercel.com'),
				site('Netlify', 'https://www.netlify.com'),
				site('Docker Hub', 'https://hub.docker.com'),
				site('npm', 'https://www.npmjs.com'),
				site('Cloudflare', 'https://dash.cloudflare.com', 'cloudflare.com'),
				site('AWS', 'https://aws.amazon.com/console', 'aws.amazon.com'),
				site('Supabase', 'https://supabase.com'),
				site('Postman', 'https://www.postman.com'),
			],
		},
		{
			id: 'crypto-finance',
			category: 'Crypto & Finance',
			icon: favicon('coinmarketcap.com'),
			badges: [{ label: 'Markets', bgColor: '#12b981', textColor: '#fff' }],
			links: [
				site('CoinMarketCap', 'https://coinmarketcap.com'),
				site('CoinGecko', 'https://www.coingecko.com'),
				site('Binance', 'https://www.binance.com'),
				site('Coinbase', 'https://www.coinbase.com'),
				site('Kraken', 'https://www.kraken.com'),
				site('TradingView', 'https://www.tradingview.com'),
				site('Yahoo Finance', 'https://finance.yahoo.com'),
				site('Investing', 'https://www.investing.com'),
				site('Wise', 'https://wise.com'),
				site('Revolut', 'https://www.revolut.com'),
				site('Stripe', 'https://dashboard.stripe.com', 'stripe.com'),
				site('PayPal', 'https://www.paypal.com'),
			],
		},
		{
			id: 'news',
			category: 'News & Signals',
			icon: favicon('reuters.com'),
			badges: [],
			links: [
				site('Reuters', 'https://www.reuters.com'),
				site('BBC', 'https://www.bbc.com/news', 'bbc.com'),
				site('Euronews', 'https://www.euronews.com'),
				site('The Guardian', 'https://www.theguardian.com'),
				site('AP News', 'https://apnews.com'),
				site('Bloomberg', 'https://www.bloomberg.com'),
				site('Financial Times', 'https://www.ft.com'),
				site('The Verge', 'https://www.theverge.com'),
				site('TechCrunch', 'https://techcrunch.com'),
				site('Hacker News', 'https://news.ycombinator.com'),
				site('Product Hunt', 'https://www.producthunt.com'),
				site('Google News', 'https://news.google.com'),
			],
		},
		{
			id: 'travel-public',
			category: 'Travel & Public',
			icon: favicon('booking.com'),
			badges: [{ label: 'EU / US', bgColor: '#eef4ff', textColor: '#3151c8' }],
			links: [
				site('Google Maps', 'https://maps.google.com'),
				site('Google Flights', 'https://www.google.com/travel/flights', 'google.com'),
				site('Booking', 'https://www.booking.com'),
				site('Airbnb', 'https://airbnb.com'),
				site('Skyscanner', 'https://www.skyscanner.net'),
				site('Trainline', 'https://www.thetrainline.com'),
				site('Uber', 'https://uber.com'),
				site('DHL', 'https://www.dhl.com'),
				site('UPS', 'https://www.ups.com/track', 'ups.com'),
				site('GOV.UK', 'https://www.gov.uk'),
				site('EU Portal', 'https://european-union.europa.eu', 'europa.eu'),
				site('IRS', 'https://www.irs.gov'),
			],
		},
		{
			id: 'social-creative',
			category: 'Social & Creative',
			icon: favicon('instagram.com'),
			badges: [],
			links: [
				site('X', 'https://x.com'),
				site('LinkedIn', 'https://linkedin.com'),
				site('Instagram', 'https://instagram.com'),
				site('Reddit', 'https://reddit.com'),
				site('Discord', 'https://discord.com'),
				site('WhatsApp', 'https://web.whatsapp.com'),
				site('Telegram', 'https://web.telegram.org'),
				site('Pinterest', 'https://pinterest.com'),
				site('YouTube', 'https://youtube.com'),
				site('Spotify', 'https://open.spotify.com', 'spotify.com'),
				site('Behance', 'https://www.behance.net'),
				site('Dribbble', 'https://dribbble.com'),
			],
		},
		{
			id: 'shopping',
			category: 'Shopping & Deals',
			icon: favicon('amazon.com'),
			badges: [],
			links: [
				site('Amazon', 'https://www.amazon.com'),
				site('eBay', 'https://www.ebay.com'),
				site('Etsy', 'https://www.etsy.com'),
				site('IKEA', 'https://www.ikea.com'),
				site('Apple', 'https://www.apple.com'),
				site('Best Buy', 'https://www.bestbuy.com'),
				site('Target', 'https://www.target.com'),
				site('Walmart', 'https://www.walmart.com'),
				site('Idealo', 'https://www.idealo.de'),
				site('CamelCamelCamel', 'https://camelcamelcamel.com'),
				site('Honey', 'https://www.joinhoney.com'),
				site('Google Shopping', 'https://shopping.google.com'),
			],
		},
		{
			id: 'learning',
			category: 'Learning',
			icon: favicon('coursera.org'),
			badges: [],
			links: [
				site('Coursera', 'https://www.coursera.org'),
				site('edX', 'https://www.edx.org'),
				site('Khan Academy', 'https://www.khanacademy.org'),
				site('Udemy', 'https://www.udemy.com'),
				site('Duolingo', 'https://www.duolingo.com'),
				site('Brilliant', 'https://brilliant.org'),
				site('MIT OpenCourseWare', 'https://ocw.mit.edu', 'mit.edu'),
				site('Google Scholar', 'https://scholar.google.com', 'scholar.google.com'),
				site('Archive', 'https://archive.org'),
				site('TED', 'https://www.ted.com'),
				site('OpenStax', 'https://openstax.org'),
				site('WolframAlpha', 'https://www.wolframalpha.com'),
			],
		},
	],
}
