import { Theme } from '@/context/theme.context'
import type { MarketResponse, UserInventoryResponse } from '@/services/hooks/market/market.interface'

export const localMarketItems: MarketResponse = {
	totalPages: 1,
	items: [
		{
			id: 'local-theme-glass',
			name: 'Glass interface',
			description: 'A translucent interface style with soft depth and crisp contrast.',
			type: 'THEME',
			price: 0,
			meta: {},
			previewUrl: null,
			itemValue: Theme.Glass,
			isOwned: true,
		},
		{
			id: 'local-theme-icy',
			name: 'Icy blue',
			description: 'A calm blue theme tuned for bright wallpapers and daylight work.',
			type: 'THEME',
			price: 0,
			meta: {},
			previewUrl: null,
			itemValue: Theme.Icy,
			isOwned: true,
		},
		{
			id: 'local-theme-dark',
			name: 'Midnight core',
			description: 'A restrained dark theme for low-light browsing.',
			type: 'THEME',
			price: 0,
			meta: {},
			previewUrl: null,
			itemValue: Theme.Dark,
			isOwned: true,
		},
		{
			id: 'local-theme-light',
			name: 'Daylight',
			description: 'A clean light theme for high visibility and simple contrast.',
			type: 'THEME',
			price: 0,
			meta: {},
			previewUrl: null,
			itemValue: Theme.Light,
			isOwned: true,
		},
		{
			id: 'local-title-focus',
			name: 'Focus title',
			description: 'A minimal browser title for deep work sessions.',
			type: 'BROWSER_TITLE',
			price: 0,
			meta: { template: 'LiveDash • Focus Mode' },
			previewUrl: null,
			itemValue: 'LiveDash • Focus Mode',
			isOwned: true,
		},
		{
			id: 'local-title-studio',
			name: 'Studio title',
			description: 'A polished title preset for creative workflows.',
			type: 'BROWSER_TITLE',
			price: 0,
			meta: { template: 'LiveDash Studio' },
			previewUrl: null,
			itemValue: 'LiveDash Studio',
			isOwned: true,
		},
		{
			id: 'local-title-command',
			name: 'Command title',
			description: 'A sharp title for operators who use the dashboard as mission control.',
			type: 'BROWSER_TITLE',
			price: 0,
			meta: { template: 'LiveDash Command' },
			previewUrl: null,
			itemValue: 'LiveDash Command',
			isOwned: true,
		},
		{
			id: 'local-title-market',
			name: 'Market pulse title',
			description: 'A title preset for crypto, markets, and live signal workflows.',
			type: 'BROWSER_TITLE',
			price: 0,
			meta: { template: 'LiveDash • Market Pulse' },
			previewUrl: null,
			itemValue: 'LiveDash • Market Pulse',
			isOwned: true,
		},
		{
			id: 'local-font-system',
			name: 'System UI',
			description: 'A native, fast, platform-aligned dashboard font.',
			type: 'FONT',
			price: 0,
			meta: {},
			previewUrl: null,
			itemValue: 'system-ui',
			isOwned: true,
		},
		{
			id: 'local-font-inter',
			name: 'Inter',
			description: 'A neutral interface font with excellent readability.',
			type: 'FONT',
			price: 0,
			meta: {},
			previewUrl: null,
			itemValue: 'Inter',
			isOwned: true,
		},
		{
			id: 'local-font-serif',
			name: 'Editorial serif',
			description: 'A refined serif option for a more editorial surface.',
			type: 'FONT',
			price: 0,
			meta: {},
			previewUrl: null,
			itemValue: 'Georgia, serif',
			isOwned: true,
		},
		{
			id: 'local-font-mono',
			name: 'Mono desk',
			description: 'A precise mono-style look for technical workflows.',
			type: 'FONT',
			price: 0,
			meta: {},
			previewUrl: null,
			itemValue: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
			isOwned: true,
		},
	],
}

export const localUserInventory: UserInventoryResponse = {
	fonts: [],
	browser_titles: [],
	themes: [],
	pagination: {
		totalPages: 1,
		total: 0,
	},
}
