import { Theme } from '@/context/theme.context'
import type { MarketResponse, UserInventoryResponse } from '@/services/hooks/market/market.interface'

export const localMarketItems: MarketResponse = {
	totalPages: 1,
	items: [
		{
			id: 'local-title-focus',
			name: 'Focus title',
			description: 'A clean browser title for focused work sessions.',
			type: 'BROWSER_TITLE',
			price: 0,
			meta: { template: 'LiveDash • Focus Mode' },
			previewUrl: null,
			itemValue: 'LiveDash • Focus Mode',
			isOwned: true,
		},
		{
			id: 'local-title-studio',
			name: 'Studio title',
			description: 'A polished title style for creative dashboards.',
			type: 'BROWSER_TITLE',
			price: 0,
			meta: { template: 'LiveDash Studio' },
			previewUrl: null,
			itemValue: 'LiveDash Studio',
			isOwned: true,
		},
		{
			id: 'local-theme-glass',
			name: 'Glass interface',
			description: 'A translucent interface style with soft depth.',
			type: 'THEME',
			price: 0,
			meta: {},
			previewUrl: null,
			itemValue: Theme.Glass,
			isOwned: true,
		},
		{
			id: 'local-theme-icy',
			name: 'Icy blue',
			description: 'A bright, calm theme tuned for blue wallpapers.',
			type: 'THEME',
			price: 0,
			meta: {},
			previewUrl: null,
			itemValue: Theme.Icy,
			isOwned: true,
		},
		{
			id: 'local-theme-dark',
			name: 'Dark mode',
			description: 'A restrained dark theme for low-light browsing.',
			type: 'THEME',
			price: 0,
			meta: {},
			previewUrl: null,
			itemValue: Theme.Dark,
			isOwned: true,
		},
		{
			id: 'local-font-system',
			name: 'System UI',
			description: 'A native, fast, platform-aligned dashboard font.',
			type: 'FONT',
			price: 0,
			meta: {},
			previewUrl: null,
			itemValue: 'system-ui',
			isOwned: true,
		},
		{
			id: 'local-font-serif',
			name: 'Editorial serif',
			description: 'A refined serif option for a more editorial surface.',
			type: 'FONT',
			price: 0,
			meta: {},
			previewUrl: null,
			itemValue: 'Georgia, serif',
			isOwned: true,
		},
	],
}

export const localUserInventory: UserInventoryResponse = {
	fonts: [],
	browser_titles: [],
	themes: [],
	pagination: {
		totalPages: 1,
		total: 0,
	},
}
